[General]
cmdenv-express-mode = true
cmdenv-autoflush = true
cmdenv-status-frequency = 10s
#**.cmdenv-log-level = info
**.cmdenv-log-level = off
cmdenv-performance-display = false

image-path = ../../images

network = timeoutNetwork

##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = true
print-undisposed = false

*.playgroundSizeX = 25000m
*.playgroundSizeY = 2500m
*.playgroundSizeZ = 50m


##########################################################
# Annotation parameters                                  #
##########################################################
*.annotations.draw = true

##########################################################
# Obstacle parameters                                    #
##########################################################
#*.obstacles.obstacles = xmldoc("config.xml", "//AnalogueModel[@type='SimpleObstacleShadowing']/obstacles")
#*obstacles.debug = false

##########################################################
#            TraCIScenarioManager parameters             #
##########################################################
*.manager.updateInterval = 0.1s
*.manager.host = "localhost"
*.manager.port = 9999
*.manager.autoShutdown = true
*.manager.launchConfig = xmldoc("line.launchd.xml")

##########################################################
#                       RSU SETTINGS                     #
#                                                        #
#                                                        #
##########################################################
#*.rsu[0].mobility.x = 2000
#*.rsu[0].mobility.y = 2000
#*.rsu[0].mobility.z = 3

#*.rsu[*].applType = "TraCIDemoRSU11p"
#*.rsu[*].appl.headerLength = 80 bit
#*.rsu[*].appl.sendBeacons = false
#*.rsu[*].appl.dataOnSch = false
#*.rsu[*].appl.beaconInterval = 1s
#*.rsu[*].appl.beaconUserPriority = 7
#*.rsu[*].appl.dataUserPriority = 5
#*.rsu[*].nic.phy80211p.antennaOffsetZ = 0 m

##########################################################
#            11p specific parameters                     #
#                                                        #
#                    NIC-Settings                        #
##########################################################
*.connectionManager.sendDirect = true
*.connectionManager.maxInterfDist = 2600m
*.connectionManager.drawMaxIntfDist = false

*.**.nic.mac1609_4.useServiceChannel = false

*.**.nic.mac1609_4.txPower = 20mW
*.**.nic.mac1609_4.bitrate = 6Mbps #also decides modulation scheme
*.**.nic.phy80211p.minPowerLevel = -110dBm

*.**.nic.phy80211p.useNoiseFloor = true
*.**.nic.phy80211p.noiseFloor = -98dBm

*.**.nic.phy80211p.decider = xmldoc("config.xml")
*.**.nic.phy80211p.analogueModels = xmldoc("config.xml")
*.**.nic.phy80211p.usePropagationDelay = true

*.**.nic.phy80211p.antenna = xmldoc("antenna.xml", "/root/Antenna[@id='monopole']")
*.node[*].nic.phy80211p.antennaOffsetY = 0 m
*.node[*].nic.phy80211p.antennaOffsetZ = 1.895 m

##########################################################
#                      App Layer                         #
##########################################################
*.node[*].applType = "MyVeinsApp"
*.node[*].appl.headerLength = 80 bit
*.node[*].appl.dataLengthBits = 1024 bit
*.node[*].appl.sendBeacons = false
*.node[*].appl.dataOnSch = false
*.node[*].appl.beaconInterval = 1s

##########################################################
#                      Mobility                          #
##########################################################
*.node[*].veinsmobility.x = 0
*.node[*].veinsmobility.y = 0
*.node[*].veinsmobility.z = 0
*.node[*].veinsmobility.setHostSpeed = true
*.node[*0].veinsmobility.accidentCount = 0
*.node[*0].veinsmobility.accidentStart = 73s
*.node[*0].veinsmobility.accidentDuration = 50s

**.vector-recording = false
**.scalar-recording = true
# *.node[*].nic.phy80211p.collectCollisionStatistics = true 

sim-time-limit = 20s #150
*.node[*].appl.start = 2s
*.node[*].appl.interval = 20s # removed intervall msging right now and data collecting is made for single msging
*.node[*].appl.timeoutMin = 0s
#*.node[*].appl.timeoutMax = ${timeoutMax = 0.000..0.004 step 0.00005}s
#*.node[*].appl.timeoutMax = ${timeoutMax = 0.0000..0.060 step 0.001}s
#*.node[*].appl.timeoutMax = ${timeoutMax = 0.004..0.02 step 0.0005}s
#*.node[*].appl.timeoutMax = ${timeoutMax = 95..100 step 1}s
#*.node[*].appl.timeoutMax = ${timeoutMax = 56}ms
#*.node[*].appl.timeoutMax = ${timeoutMax = 25..30 step 1}ms
*.node[*].appl.timeoutMax = ${timeoutMax = 0..60 step 1}ms

repeat = 1000 # 30
*.node[*].appl.timeoutType = 2 # 0 is no mods, 1 is distance based, 2 is signal power based. timeoutType is an extra modifier for the window. 
*.node[*].appl.distanceLock = 3 # 0=NOMOD 1=FIRST25 2=FIRST50 3=FIRST75 for distance based: makes timeoutmin bigger so later percent of vehicles are forced as relays if they are reached 
*.node[*].appl.scalingDistance = 620
seed-set = ${timeoutMax}0000${repetition}
*.manager.seed = ${timeoutMax}0000${repetition}
result-dir = /home/veins/storage/result
output-scalar-file = ${resultdir}/${timeoutMax}_${repetition}.sca
### output-vector-file = ${resultdir}/${timeoutMax}_${repetition}.vec
[Config Default]

[Config NoGui]
*.manager.ignoreGuiCommands = true

#[Config WithBeaconing]
#*.rsu[*].appl.sendBeacons = true
#*.node[*].appl.sendBeacons = true

#[Config WithChannelSwitching]
#*.**.nic.mac1609_4.useServiceChannel = true
#*.node[*].appl.dataOnSch = true
#*.rsu[*].appl.dataOnSch = true
